# Generated by Django 5.0.1 on 2025-06-14 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0003_alter_cita_fecha_alter_cita_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(default='fas fa-pills', max_length=50)),
            ],
            options={
                'verbose_name': 'Categoría de Farmacia',
                'verbose_name_plural': 'Categorías de Farmacia',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_generico', models.CharField(blank=True, max_length=200)),
                ('tipo', models.CharField(choices=[('antibiotico', 'Antibiótico'), ('analgesico', 'Analgésico'), ('antiinflamatorio', 'Antiinflamatorio'), ('antiparasitario', 'Antiparasitario'), ('vitamina', 'Vitamina/Suplemento'), ('vacuna', 'Vacuna'), ('desparasitante', 'Desparasitante'), ('dermatologico', 'Dermatológico'), ('cardiaco', 'Cardíaco'), ('digestivo', 'Digestivo'), ('respiratorio', 'Respiratorio'), ('oftalmico', 'Oftálmico'), ('otro', 'Otro')], max_length=20)),
                ('presentacion', models.CharField(choices=[('tableta', 'Tableta'), ('capsula', 'Cápsula'), ('jarabe', 'Jarabe'), ('suspension', 'Suspensión'), ('inyectable', 'Inyectable'), ('crema', 'Crema'), ('pomada', 'Pomada'), ('gotas', 'Gotas'), ('spray', 'Spray'), ('polvo', 'Polvo')], max_length=20)),
                ('concentracion', models.CharField(help_text='Ej: 250mg, 10ml, etc.', max_length=100)),
                ('laboratorio', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('indicaciones', models.TextField(help_text='Para qué se usa')),
                ('contraindicaciones', models.TextField(blank=True, help_text='Cuándo no usar')),
                ('efectos_secundarios', models.TextField(blank=True)),
                ('dosis_recomendada', models.TextField(help_text='Dosis general recomendada')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=5)),
                ('requiere_receta', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='medicamentos/')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.categoriafarmacia')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RecetaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(help_text='Fecha límite para usar la receta')),
                ('diagnostico', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('parcialmente_dispensada', 'Parcialmente Dispensada'), ('dispensada', 'Completamente Dispensada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='activa', max_length=25)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='veterinaria.cita')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.mascota')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.veterinario')),
            ],
            options={
                'verbose_name': 'Receta Médica',
                'verbose_name_plural': 'Recetas Médicas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='ItemReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('dosis', models.CharField(help_text='Ej: 1 tableta cada 8 horas', max_length=200)),
                ('duracion', models.CharField(help_text='Ej: 7 días, 2 semanas', max_length=100)),
                ('instrucciones', models.TextField(blank=True, help_text='Instrucciones especiales')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.medicamento')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='veterinaria.recetamedica')),
            ],
            options={
                'verbose_name': 'Item de Receta',
                'verbose_name_plural': 'Items de Receta',
            },
        ),
        migrations.CreateModel(
            name='ReservaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receta', 'Con Receta Médica'), ('libre', 'Venta Libre')], max_length=10)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_retiro', models.DateField(help_text='Fecha estimada de retiro')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('lista', 'Lista para Recoger'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas', models.TextField(blank=True)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veterinaria.recetamedica')),
            ],
            options={
                'verbose_name': 'Reserva de Medicamento',
                'verbose_name_plural': 'Reservas de Medicamentos',
                'ordering': ['-fecha_reserva'],
            },
        ),
        migrations.CreateModel(
            name='ItemReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.medicamento')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='veterinaria.reservamedicamento')),
            ],
            options={
                'verbose_name': 'Item de Reserva',
                'verbose_name_plural': 'Items de Reserva',
            },
        ),
    ]
