# Generated by Django 5.0.1 on 2025-06-16 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0005_mascota_propietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicioPeluqueria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(default='fas fa-cut', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Servicio de Peluquería',
                'verbose_name_plural': 'Categorías de Servicios de Peluquería',
            },
        ),
        migrations.CreateModel(
            name='CitaPeluqueria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió')], default='programada', max_length=20)),
                ('observaciones_cliente', models.TextField(blank=True, help_text='Observaciones del cliente')),
                ('observaciones_peluquero', models.TextField(blank=True, help_text='Notas del peluquero')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.mascota')),
            ],
            options={
                'verbose_name': 'Cita de Peluquería',
                'verbose_name_plural': 'Citas de Peluquería',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='FotosAntesDepues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_antes', models.ImageField(blank=True, null=True, upload_to='peluqueria/antes/')),
                ('foto_despues', models.ImageField(blank=True, null=True, upload_to='peluqueria/despues/')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='veterinaria.citapeluqueria')),
            ],
            options={
                'verbose_name': 'Fotos Antes/Después',
                'verbose_name_plural': 'Fotos Antes/Después',
            },
        ),
        migrations.CreateModel(
            name='Peluquero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('experiencia_años', models.PositiveIntegerField(default=0)),
                ('certificaciones', models.TextField(blank=True, help_text='Certificaciones y cursos')),
                ('horario_inicio', models.TimeField(default='09:00')),
                ('horario_fin', models.TimeField(default='18:00')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('especialidades', models.ManyToManyField(blank=True, to='veterinaria.categoriaserviciopeluqueria')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Peluquero',
                'verbose_name_plural': 'Peluqueros',
            },
        ),
        migrations.AddField(
            model_name='citapeluqueria',
            name='peluquero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinaria.peluquero'),
        ),
        migrations.CreateModel(
            name='ServicioPeluqueria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_estimada', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('tipo_mascota', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ambos', 'Perros y Gatos')], default='ambos', max_length=10)),
                ('tamaño_mascota', models.CharField(choices=[('pequeño', 'Pequeño (hasta 10kg)'), ('mediano', 'Mediano (10-25kg)'), ('grande', 'Grande (25-40kg)'), ('gigante', 'Gigante (más de 40kg)'), ('todos', 'Todos los tamaños')], default='todos', max_length=10)),
                ('incluye', models.TextField(help_text='Qué incluye el servicio')),
                ('recomendaciones', models.TextField(blank=True, help_text='Recomendaciones especiales')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='peluqueria/')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.categoriaserviciopeluqueria')),
            ],
            options={
                'verbose_name': 'Servicio de Peluquería',
                'verbose_name_plural': 'Servicios de Peluquería',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioCitaPeluqueria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True, help_text='Notas específicas para este servicio')),
                ('completado', models.BooleanField(default=False)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='veterinaria.citapeluqueria')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.serviciopeluqueria')),
            ],
            options={
                'verbose_name': 'Servicio de Cita de Peluquería',
                'verbose_name_plural': 'Servicios de Citas de Peluquería',
            },
        ),
    ]
