# Generated by Django 5.0.1 on 2025-06-17 02:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0006_categoriaserviciopeluqueria_citapeluqueria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmaceutico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message="El número debe estar en formato: '+999999999'")])),
                ('numero_registro', models.CharField(help_text='Número de registro profesional', max_length=20, unique=True)),
                ('especialidad', models.CharField(default='Farmacia General', max_length=100)),
                ('experiencia_años', models.PositiveIntegerField(default=0)),
                ('certificaciones', models.TextField(blank=True, help_text='Certificaciones y cursos especializados')),
                ('horario_inicio', models.TimeField(default='08:00')),
                ('horario_fin', models.TimeField(default='20:00')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmacéutico',
                'verbose_name_plural': 'Farmacéuticos',
            },
        ),
    ]
